feat!: update token structure to remove product contexts and screen size tokens
- Removes `frozenproduct` and `product` contexts from output.
- Removes screen size level to token output.
- Removes `all.css` file from output.
- Removes `ios` format from output.
- Renames `typography` tokens to `font`.
- Removes `form` and `status` tokens.
- Removes specific `spacing`, `font`, `size`, `radius`, `borderWidth`
and `shadow` tokens for `components` in favour of `global`.
- Removes comments from output.
- Ensures `components` tokens in all outputted formats resolve to
references rather than values to support white-labelling.
- Adds `message` and `pill` to `components` tokens.
- Adds `inverse` tokens for the following `components`:
  - `container` (Tile and Card) status borders.
  - `input` validation bars and label sets.
  - Sage `logo`.
  - AI `sparkle` and `loader`.

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -5,7 +5,7 @@ on:
       - master
       - rc-updates
       - rc-staged
-      
+
 jobs:
   run-linters:
     name: Run linters
@@ -41,3 +41,23 @@ jobs:
         run: |
           # Find all JSON files in dist directory and run validation
           npx jsonlint ./dist/**/*.json --no-duplicate-keys
+
+      - name: Check for [object Object] in SCSS
+        run: |
+          if grep -r '\[object Object\]' dist/scss; then
+            echo "Error: Found [object Object] in SCSS files."
+            exit 1
+          fi
+
+      - name: Compile SCSS
+        run: |
+          (
+            echo "@import 'global.scss';"
+            echo "@import 'dark.scss';"
+            echo "@import 'light.scss';"
+            for f in dist/scss/components/*.scss; do
+              fname=$(basename "$f")
+              echo "@import 'components/$fname';"
+            done
+          ) > dist/scss/index.scss
+          npx sass dist/scss/index.scss dist/scss/index.css
